name:    sound-room
version: "1.0.0"

dependencies:

- base 
- websockets
- uuid
- text
- bytestring

# Runnable executable for our application
executables:
  sound-room:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
