name:    sound-room
version: "0.0.1"

dependencies:

- base 
- websockets
- uuid
- text

# Runnable executable for our application
executables:
  sound-room:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
